### ISSUE TITLE
Arkadaş down olmuş

### ISSUE THREAD

**Issue by keyiflerolsun** [sh4dowb/udemy-free-courses#1]
Aracı elden geçirme şansınız var mı :

**Comment by sh4dowb** [comment]
merhabalar, biraz geç oldu kusura bakmayın, yeni gördüm :D 
udemy auto buy çalışıyor mu denemedim, diğer toolu düzelttim şimdilik çalışıyor
eğer o da bozuksa yine issue açarsanız bakabilirim
